---
version: "3.8"
services:
  forecasting-service:
    image: dhavalsalwala/forecasting-service:0.5.2
    hostname: forecasting-service
    container_name: forecasting-service
    build:
      context: "."
    shm_size: "10.24gb"
    environment:
      MODELARDB_HOSTNAME: ${MODELARDB_HOSTNAME}
      MODELARDB_PORT: ${MODELARDB_PORT}
      MODELARDB_INTERFACE: ${MODELARDB_INTERFACE}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_CONSUMER_QUEUE: ${RABBITMQ_CONSUMER_QUEUE}
      RABBITMQ_PRODUCER_QUEUE: ${RABBITMQ_PRODUCER_QUEUE}
      TUNE_DISABLE_SIGINT_HANDLER: 1
    entrypoint: ["python", "forecasting_service/run.py", "--data_dir", "/data"]
    volumes:
      - ./data:/data

networks:
  default:
    name: more-network
    external: true
