---
version: "3.8"
services:
  forecasting-grpc-server:
    image: dhavalsalwala/forecasting-grpc-server:latest
    hostname: forecasting-grpc-server
    container_name: forecasting
    network_mode: host
    build:
      context: "."
    shm_size: "10.24gb"
    tty:
      true
    ports:
      - 50051:50051
    environment:
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_CONSUMER_QUEUE: ${RABBITMQ_CONSUMER_QUEUE}
      RABBITMQ_PRODUCER_QUEUE: ${RABBITMQ_PRODUCER_QUEUE}
      GRPC_HOST: ${GRPC_HOST}
      GRPC_PORT: ${GRPC_PORT}
    entrypoint: ["python", "serving/grpc_server.py"]

# networks:
#   default:
#     name: more-network
#     external: true
