apiVersion: v1
kind: ConfigMap
metadata:
  name: modelardb-configmap
  namespace: modelardb
data:
    MODELARDB_HOSTNAME: modelardbd-service
    MODELARDB_PORT: "9999"
    MODELARDBD_PORT: "9997"
    MODELARDB_INTERFACE: arrow
    AWS_DEFAULT_REGION: eu-central-1
    AWS_ENDPOINT: http://minio-service:9000
    AWS_ALLOW_HTTP: "true"
    MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: "640"
    MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: "10000"
    MODELARDBD_TRANSFER_BATCH_SIZE_IN_BYTES: "10000"
    POSTGRES_DB_HOST: postgres-service
    POSTGRES_USER: modelardb_user
    POSTGRES_PASSWORD: modelardb_password
    POSTGRES_DB: metadata
    PGGSSENCMODE: disable
    MODELARDB_MANAGER_PORT: modelardb-service