---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio-storage
  local:
    path: /data/1/k8s/minio_data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key:  node-role.kubernetes.io/control-plane
          operator: Exists 