---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: modelardb
spec:
  storageClassName: minio-storage
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteMany