---
sail:

  model_path: null

  estimators:
    - name: linear_reg
      class: sail.models.river.linear_model.LinearRegression
      params:
        - name: optimizer
          class: river.optim.SGD
          params:
            - name: lr
              value: 0.1
        - name: intercept_init
          value: 0.15
    - name: random_forest
      class: sail.models.river.forest.AdaptiveRandomForestRegressor
      params:
        - name: n_models
          value: 10

  steps:
    - name: Imputer
      class: sklearn.impute.SimpleImputer
      params:
        - name: missing_values
          class: numpy.nan
        - name: strategy
          value: mean
    - name: standard_scalar
      class: sail.transfomers.river.preprocessing.StandardScaler
    - name: regressor
      value: passthrough

  sail_pipeline:
    params:
    - name: scoring
      class: river.metrics.R2
    - name: verbosity
      value: 1
    
  parameter_grid:
    - regressor:
        - linear_reg
      regressor__l2:
        - 0.1
        - 0.9
      regressor__intercept_init:
        - 0.2
        - 0.5
    - regressor:
        - random_forest
      regressor__n_models:
        - 10
        - 15
        - 20

  search_method: SAILTuneGridSearchCV
  search_data_size: 200
  search_method_params:
    - name: verbose
      value: 1
    - name: num_cpus_per_trial
      value: 1
    - name: max_iters
      value: 1
    - name: early_stopping
      value: false
    - name: mode
      value: max
    - name: scoring
      value: r2
    - name: pipeline_auto_early_stop
      value: false
    - name: keep_best_configurations
      value: 2
    - name: cluster_address
      value: null

  incremental_training: true

  drift_detector:
    class: sail.drift_detection.drift_detector.SAILDriftDetector
    params:
    - name: model
      class: river.drift.EDDM
    - name: drift_param
      value: difference

  pipeline_strategy: DetectAndIncrement

time_series:
  model_table: wind_turbine
  target: active_power
  timestamp_col: datetime 
  selected_features: [] # empty means use all features
  classes: [] # only applicable for classification problem and when incremental_training is enabled
  from_date: null
  to_date: null
  data_limit: 500 # put null for all data
  data_batch_size: 50
  data_ingestion_freq: 0 #ingestion frequency in sec