---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-forecasting
  namespace: more-demo
  labels:
    app: grpc-forecasting
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: grpc-forecasting
  template:
    metadata:
      labels:
        app: grpc-forecasting
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: grpc-forecasting-container
        image: dhavalsalwala/forecasting-service:1.6.1
        imagePullPolicy: IfNotPresent
        args: ["--data_dir", "/data"]
        resources: {}
        volumeMounts:
          - name: forecasting-data
            mountPath: /data
            subPathExpr: $(POD_NAME)
          - name: forecasting-datasets
            mountPath: /datasets

        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MODELARDB_HOSTNAME
          valueFrom: 
            configMapKeyRef:
              name: modelardb-configmap
              key: MODELARDB_HOSTNAME
        - name: MODELARDB_PORT
          valueFrom:
            configMapKeyRef:
              name: modelardb-configmap
              key: MODELARDB_PORT
        - name: MODELARDB_INTERFACE
          valueFrom: 
            configMapKeyRef:
              name: modelardb-configmap
              key: MODELARDB_INTERFACE
        - name: LOGGING_LEVEL
          valueFrom: 
            configMapKeyRef:
              name: more-configmap
              key: LOGGING_LEVEL
        - name: RABBITMQ_USER
          valueFrom: 
            configMapKeyRef:
              name: more-configmap
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom: 
            configMapKeyRef:
              name: more-configmap
              key: RABBITMQ_PASS
        - name: RABBITMQ_HOST
          valueFrom: 
            configMapKeyRef:
              name: more-configmap
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom: 
            configMapKeyRef:
              name: more-configmap
              key: RABBITMQ_PORT
        - name: FORECASTING_CONSUMER_QUEUE
          valueFrom:
            configMapKeyRef:
              name: more-configmap
              key: GRPC_PRODUCER_QUEUE
        - name: FORECASTING_PRODUCER_QUEUE
          valueFrom:
            configMapKeyRef:
              name: more-configmap
              key: GRPC_CONSUMER_QUEUE

      volumes:
      - name: forecasting-data
        nfs:
          server: master.more2020.eu
          path: /data/1/k8s/forecasting_data/grpc
      - name: forecasting-datasets
        nfs:
          server: master.more2020.eu
          path: /data/1/k8s/datasets
