---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  podSubnet: "192.168.0.0/16"
controlPlaneEndpoint: "83.212.75.52:6443" 
kubernetesVersion: v1.27.4
clusterName: "more-cluster"

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "83.212.75.52"
  bindPort: 6443
nodeRegistration:
  name: master
  kubeletExtraArgs:
    node-labels: "node-type=master"


