---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  podSubnet: "192.168.0.0/16"
controlPlaneEndpoint: "10.242.7.73:6443" 
kubernetesVersion: v1.27.4
clusterName: "more-forecating-cluster"

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "10.242.7.73"
  bindPort: 6443
nodeRegistration:
  name: more-master
  kubeletExtraArgs:
    cloud-provider: external
    node-labels: "node-type=master"


