---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: more-demo
  labels:
    app: jaeger
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      containers:
        - name: jaeger-server
          image: jaegertracing/all-in-one:1.6
          resources: {}
          ports:
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 5778
            - containerPort: 16686
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 14250
            - containerPort: 14268
            - containerPort: 14269
            - containerPort: 9411
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: more-demo
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
    - name: jaeger-udp
      protocol: UDP
      port: 6831
      targetPort: 6831
      nodePort: 31831
    - name: web-ui
      protocol: TCP
      port: 16686
      targetPort: 16686
      nodePort: 31686
