apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: d7u059.vte5dsux932wl7f4
    apiServerEndpoint: "10.242.7.73:6443"
    caCertHashes: ["sha256:24df2e2f8b577c337eaece255d2b2453ac340deea634e0901b475910470120d3"]
nodeRegistration:
  name: more-worker
  kubeletExtraArgs:
    cloud-provider: external
    node-labels: "node-role.kubernetes.io/worker="
