---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging
  namespace: more-demo
  labels:
    app: messaging
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: messaging
  template:
    metadata:
      labels:
        app: messaging
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      containers:
      - name: messaging-container
        image: rabbitmq:3-management-alpine
        resources: {}
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom: 
            configMapKeyRef:
              name: more-configmap
              key: RABBITMQ_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom: 
            configMapKeyRef:
              name: more-configmap
              key: RABBITMQ_PASS
        ports:
        - containerPort: 5672
        - containerPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: more-demo
spec:
  type: NodePort
  selector:
    app: messaging
  ports:
    - name: service
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 32000
    - name: admin
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 32001