# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: modelardbd
#   namespace: more-demo
#   labels:
#     app: modelardbd
# spec:
#   replicas: 1
#   selector: 
#     matchLabels:
#       app: modelardbd
#   template:
#     metadata:
#       labels:
#         app: modelardbd
#     spec:
#       containers:
#       - name: modelardbd-rs-container
#         image: dhavalsalwala/modelardb-rs:latest
#         volumeMounts:
#           - mountPath: /data
#             name: modelardbd-data
#         resources: {}
#         ports:
#         - containerPort: 9999
#       volumes:
#         - name: modelardbd-data
#           persistentVolumeClaim:
#             claimName: modelardbd-pvc

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: modelardbd
  namespace: more-demo
  labels:
    app: modelardbd
spec:
  replicas: 1
  serviceName: modelardbd
  selector: 
    matchLabels:
      app: modelardbd
  template:
    metadata:
      labels:
        app: modelardbd
    spec:
      containers:
      - name: modelardbd-rs
        image: dhavalsalwala/modelardb-rs:1Nov23
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /data
            name: modelardbd-pvc
        resources: {}
        ports:
        - containerPort: 9999
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom: 
              secretKeyRef:
                name: more-secret
                key: MINIO_ROOT_USER
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom: 
              secretKeyRef:
                name: more-secret
                key: MINIO_ROOT_PASSWORD
          - name: AWS_DEFAULT_REGION
            valueFrom: 
              configMapKeyRef:
                name: more-configmap
                key: AWS_DEFAULT_REGION
          - name: AWS_ENDPOINT
            valueFrom: 
              configMapKeyRef:
                name: more-configmap
                key: AWS_ENDPOINT
          - name: AWS_ALLOW_HTTP
            valueFrom: 
              configMapKeyRef:
                name: more-configmap
                key: AWS_ALLOW_HTTP
        command: ["target/release/modelardbd", "edge", "/data", "s3://modelardata"]

  volumeClaimTemplates:
  - metadata:
      name: modelardbd-pvc
    spec:
      accessModes:
      - ReadWriteMany
      storageClassName: modelardbd-storage
      resources:
        requests:
          storage: 100Gi
      

---
apiVersion: v1
kind: Service
metadata:
  name: modelardbd-service
  namespace: more-demo
spec:
  type: NodePort
  selector:
    app: modelardbd
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
      nodePort: 31000
