---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: modelardb
  namespace: more-demo
  labels:
    app: modelardb
spec:
  replicas: 1
  serviceName: modelardb
  selector: 
    matchLabels:
      app: modelardb
  template:
    metadata:
      labels:
        app: modelardb
    spec:
      containers:
      - name: modelardb-rs
        image: dhavalsalwala/modelardb-rs:1Nov23
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /data
            name: modelardb-pvc
        resources: {}
        ports:
        - containerPort: 9999
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom: 
              secretKeyRef:
                name: modelardb-secret
                key: MINIO_ROOT_USER
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom: 
              secretKeyRef:
                name: modelardb-secret
                key: MINIO_ROOT_PASSWORD
          - name: AWS_DEFAULT_REGION
            valueFrom: 
              configMapKeyRef:
                name: modelardb-configmap
                key: AWS_DEFAULT_REGION
          - name: AWS_ENDPOINT
            valueFrom: 
              configMapKeyRef:
                name: modelardb-configmap
                key: AWS_ENDPOINT
          - name: AWS_ALLOW_HTTP
            valueFrom: 
              configMapKeyRef:
                name: modelardb-configmap
                key: AWS_ALLOW_HTTP
        command: ["target/release/modelardbd", "edge", "/data"]

  volumeClaimTemplates:
  - metadata:
      name: modelardb-pvc
    spec:
      accessModes:
      - ReadWriteMany
      storageClassName: modelardb-storage
      resources:
        requests:
          storage: 100Gi
      

---
apiVersion: v1
kind: Service
metadata:
  name: modelardb-service
  namespace: more-demo
spec:
  type: NodePort
  selector:
    app: modelardb
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
      nodePort: 31000