# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: modelardbd-storage
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: modelardbd-pv-2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: modelardbd-storage
  local:
    path: /home/dhaval/dev/modelardb_data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key:  node-role.kubernetes.io/control-plane
          operator: Exists 

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: forecasting-pv
# spec:
#   capacity:
#     storage: 5Gi
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: forecasting-storage
#   hostPath:
#     path: /home/dhaval/dev/data