# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: forecasting-nfs
#   namespace: more-demo
# spec:
#   storageClassName: nfs-client
#   resources:
#     requests:
#       storage: 10Gi
#   volumeMode: Filesystem
#   accessModes:
#    - ReadWriteMany

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modelardb-pvc
  namespace: modelardb
spec:
  storageClassName: modelardb-storage
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteMany